version: "3.3"

services:

  nodered:
    build:
      context: ./nodered
      args:
        USER_ID: "${USER_ID}"
    image: nodered
    environment:
      NODE_PATH: "/data/workspace/node-red/node_modules"
      WORKDIR: "/data/workspace"
    ports:
      - "1881:8888"
      - "1880:1880"
    restart: always
    volumes:
      - ./volumes/workspace:/data/workspace
    container_name: nodered
